Resources:
  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: us-east-1a
      ImageId: ami-0440d3b780d96b29d
      InstanceType: t2.micro
      Tags:
        - Key: Name
          Value: first-web-instance
        - Key: Environment
          Value: development
        - Key: Application
          Value: web